apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: webserver-claim2
  name: webserver-claim2
  namespace: dbgpt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
