apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: Kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: webserver
  name: webserver
  namespace: dbgpt
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: Kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: webserver
    spec:
      containers:
        - args:
            - dbgpt
            - start
            - webserver
            - --config
            - /app/configs/dbgpt-proxy-siliconflow-mysql.toml
          env:
            - name: MYSQL_DATABASE
              value: dbgpt
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PASSWORD
              value: aa123456
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: SILICONFLOW_API_KEY
          image: eosphorosai/dbgpt-openai:v0.7.0
          name: webserver
          ports:
            - containerPort: 5670
              protocol: TCP
          volumeMounts:
            - mountPath: /app/configs
              name: webserver-cm0
            - mountPath: /data
              name: webserver-claim1
            - mountPath: /app/models
              name: webserver-claim2
            - mountPath: /app/pilot/data
              name: dbgpt-data
            - mountPath: /app/pilot/message
              name: dbgpt-message
      restartPolicy: Always
      volumes:
        - configMap:
            name: webserver-cm0
          name: webserver-cm0
        - name: webserver-claim1
          persistentVolumeClaim:
            claimName: webserver-claim1
        - name: webserver-claim2
          persistentVolumeClaim:
            claimName: webserver-claim2
        - name: dbgpt-data
          persistentVolumeClaim:
            claimName: dbgpt-data
        - name: dbgpt-message
          persistentVolumeClaim:
            claimName: dbgpt-message