apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: Kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: Kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: aa123456
            - name: MYSQL_USER
              value: user
          image: mysql/mysql-server
          name: db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: dbgpt-myql-db
            - mountPath: /etc/my.cnf
              name: db-cm1
              subPath: my.cnf
            - mountPath: /docker-entrypoint-initdb.d
              name: db-cm2
      restartPolicy: Always
      volumes:
        - name: dbgpt-myql-db
          persistentVolumeClaim:
            claimName: dbgpt-myql-db
        - configMap:
            items:
              - key: my.cnf
                path: my.cnf
            name: db-cm1
          name: db-cm1
        - configMap:
            name: db-cm2
          name: db-cm2
        - configMap:
            items:
              - key: dbgpt.sql
                path: dbgpt.sql
            name: db-cm3
          name: db-cm3
